name: Continuous Integration

on:
  workflow_call:
  push:
    branches:
      - features/**
  pull_request:
    branches:
      - main

jobs:
  ci_check:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[no ci-cd]') &&
      !contains(github.event.head_commit.message, '[no ci]')
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: 4. Run Lint & Run Tests
        run : |
          echo "Starting Linting..."
          npm run lint
          echo "Starting Unit & Integration Tests..."
          npm run test -- --ci
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: 5. Run Next.js Build Verification
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

